### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by pwujek** [shuangwhywhy/webpack-shebang-plugin#7]
Getting the above error with this config (see full error output below):

```javascript
const path = require('path');
const webpack = require('webpack');
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
const ShebangPlugin = require('webpack-shebang-plugin');

module.exports = {
  target: 'node',
  entry: {
    app: ['./src/main.ts']
  },
  resolve: {
    extensions: ['.ts', '.js', '.json'],
    alias: {},
    modules: [path.resolve(__dirname, '../node_modules'), '../server/node_modules']
  },
  mode: 'production',
  node: {
    __filename: false,
    __dirname: false
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        use: 'ts-loader',
        test: /\.ts?$/,
        exclude: /node_module/
      }
    ]
  },
  plugins: [
    new ShebangPlugin(),
    new webpack.EnvironmentPlugin({
    NODE_ENV: 'prod'
    }),
    // don't show warnings for unused DB packages, and some other warnings
    new FilterWarningsPlugin({
      exclude: [
        /@sap/,
        /class-transformer/,
        /(hdb|hdb-pool)/,
        /memcpy/,
        /mongodb/,
        /mssql/,
        /oracledb/,
        /pg/,
        /redis/,
        /sqlite3/,
        /sql.js/,
        /react-native-sqlite-storage/,
        /request.of.a.dependency.is.an.expression/,
        /You.may.need.an.appropriate.loader.to.handle.this.file.type/
      ]
    })
  ],
  externals: {
    '@nestjs/microservices': 'nestjs/microservices',
    'cache-manager': 'cache-manager',
    'fastify-swagger': 'fastify-swagger',
    'aws-sdk': 'aws-sdk'
  }
};

```

```
TypeError: Cannot read property '0' of undefined
    at /home/paul/Desktop/aaa/project/events/server/node_modules/webpack-shebang-plugin/index.js:27:43
    at SyncBailHook.eval [as call] (eval at create (/home/paul/Desktop/aaa/project/events/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at SyncBailHook.lazyCompileHook (/home/paul/Desktop/aaa/project/events/node_modules/tapable/lib/Hook.js:154:20)
    at WebpackOptionsApply.process (/home/paul/Desktop/aaa/project/events/node_modules/webpack/lib/WebpackOptionsApply.js:291:30)
    at webpack (/home/paul/Desktop/aaa/project/events/node_modules/webpack/lib/webpack.js:57:48)
    at processOptions (/home/paul/Desktop/aaa/project/events/node_modules/webpack-cli/bin/cli.js:272:16)
    at /home/paul/Desktop/aaa/project/events/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/paul/Desktop/aaa/project/events/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/paul/Desktop/aaa/project/events/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/paul/Desktop/aaa/project/events/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/paul/Desktop/aaa/project/events/server/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by shuangwhywhy** [comment]
@pwujek Which version of Webpack are you using?

**Comment by shuangwhywhy** [comment]
Added support for webpack 4, please check. @pwujek
